### ISSUE TITLE
createDir() complains about missing Config

### ISSUE THREAD

**Issue by alexvanniel** [josbeir/cakephp-filesystem#12]
When I do the following:

$this->getFilesystem('default')->getAdapter()->createDir($cacheBasePath);

I get an error saying that createDir needs 2 arguments. I figured out it needs \League\Flysystem\Config so I added this. Now the error disappears but the folder is never created.

Do you have any ideas if I am doing something wrong?

**Comment by josbeir** [comment]
$this->getFilesystem('default')->getAdapter() returns the configured flysystem adapter. So in this case you should check the flysystem api / issue tracker 

=> https://flysystem.thephpleague.com/v1/docs/usage/filesystem-api/

Are you writing to AWS? 

> Some filesystems don’t require directories at all, and for those filesystems (like AWS S3) no directories are created when writing files.

**Comment by alexvanniel** [comment]
No, I am writing to a local adapter. The official API documentation doesn't mention a second argument that would be needed. That is why I got these errors to begin with ...

**Comment by josbeir** [comment]
Maybe related to https://github.com/thephpleague/flysystem/issues/739 ? 
Still something flysystem related i think...

**Comment by alexvanniel** [comment]
I guess it is. Sorry to pollute your issue tracker with this. I will move over to flysystem and see if I can find there.
