### ISSUE TITLE
Please, update to be compatible with league/flysystem v3 

### ISSUE THREAD

**Issue by progdog-ru** [josbeir/cakephp-filesystem#13]

**Comment by josbeir** [comment]
https://github.com/josbeir/cakephp-filesystem/releases/tag/3.0-alpha.1

Your wish is my command. Tests are passing but haven't really used it in production so be sure to give feedback in something fails :-)

**Comment by saeideng** [comment]
@josbeir  you can also support `league/flysystem`  `v3.0` if you supported `v2`

**Comment by josbeir** [comment]
@saeideng Thanks for pointing that out. But isn't `league/flysystem` `v3.0` `PHP 8.0` only? I would like to keep some 7 compatibility for now...

I tested it and tests pass so there's technically no problem but i'm not sure it's a good idea to force such a strict php version at this stage?

**Comment by saeideng** [comment]
you can use like this
```
"league/flysystem": "^2.0|^3.0"
```

**Comment by progdog-ru** [comment]
> https://github.com/josbeir/cakephp-filesystem/releases/tag/3.0-alpha.1
> 
> Your wish is my command. Tests are passing but haven't really used it in production so be sure to give feedback in something fails :-)

Thank You!

**Comment by josbeir** [comment]
@saeideng right ;-) 

https://github.com/josbeir/cakephp-filesystem/releases/tag/3.0-alpha.2
