### ISSUE TITLE
Document file return duplicate mime type

### ISSUE THREAD

**Issue by hardik-biztech** [josbeir/cakephp-filesystem#19]
When i have uploaded docx file which is provided below and it's returns mime type like "application/vnd.openxmlformats-officedocument.wordprocessingml.documentapplication/vnd.openxmlformats-officedocument.wordprocessingml.document", so please review this and give us support how it's returning mime type as duplicate.

[test.docx](https://github.com/josbeir/cakephp-filesystem/files/11310750/test.docx)

Package version - 1.0.4
PHP - 7.4

**Comment by josbeir** [comment]
Not sure you why are experiencing this issue.  Maybe you are calling the method twice ?

Mimetype is returned from Flysystem's api 

See https://github.com/josbeir/cakephp-filesystem/blob/3.0/src/Filesystem.php#L237
and https://flysystem.thephpleague.com/docs/usage/filesystem-api/#filesystemreadermimetype

**Comment by hardik-biztech** [comment]
vendor/league/flysystem/src/Filesystem.php
/**
     * @inheritdoc
     */
    public function getMimetype($path)
    {
        $path = Util::normalizePath($path);
        $this->assertPresent($path);

        if (( ! $object = $this->getAdapter()->getMimetype($path)) || ! array_key_exists('mimetype', $object)) {
            return false;
        }
    
        return $object['mimetype']; -> Here it is returning multiple times mime type.
    }

**Comment by hardik-biztech** [comment]
https://github.com/josbeir/cakephp-filesystem/issues/19#issuecomment-1520169969 please suggest how to resolve this issue by using this pacakge?

ASAP.

**Comment by josbeir** [comment]
as mentioned before, the issue is probably caused by flysystem. Please check there.
