### ISSUE TITLE
How to generate unique file name for each upload?

### ISSUE THREAD

**Issue by hareshpatel1990** [josbeir/cakephp-filesystem#3]
Hello there,

Thanks for this plugin. I have implemented this works well with cakephp4, now I want to ask only one thing

Is there any way to rename or generate unique file name before or after upload file?

**Comment by hareshpatel1990** [comment]
I get a method rename() as which worked for me:

`$filesystem = $this->getFilesystem('pan');`
`$fileEntity = $filesystem->upload($this->request->getData('pancard_file_name') );
$filename=$fileEntity->getFilename();
$filename=explode('.',$filename);
if(count($filename)>1){
    $extension=$filename[count($filename)-1];
}
$newfilename=$fileEntity->getUuid().".".$extension;
$filesystem->rename($fileEntity,$newfilename);
debug($fileEntity);`

**Comment by josbeir** [comment]
Check out the formatter section for advanced (re)naming of your files

https://github.com/josbeir/cakephp-filesystem#formatters

You could extend the DefaultFormatter and implement your own logic or rename based on an entity that already exists...
