### ISSUE TITLE
does not update composer.json.

### ISSUE THREAD

**Issue by ghost** [josbeir/cakephp-filesystem#5]
composer require josbeir/cakephp-filesystem 
does not update composer.json.

   "autoload": {
        "psr-4": {
            "App\\": "src/"
        }
    },
    "autoload-dev": {
        "psr-4": {
            "App\\Test\\": "tests/",
            "Cake\\Test\\": "vendor/cakephp/cakephp/tests/"
        }
    },

**Comment by josbeir** [comment]
Can you be more specific? What is the issue?

**Comment by ghost** [comment]
I installed the plugin with the command:
composer require josbeir / cakephp-filesystem

but, after installation, the composer.json file has not been updated. Below how the file looked after installation. No changes.

Also, VSCode does not load any reference from the plugin. In PHPStorm it loads without problems, but in VSCode it doesn't. Always accuse as a non-existent plugin error.

autoload": {
"psr-4": {
"App\": "src/"
}
},
"autoload-dev": {
"psr-4": {
"App\Test\": "tests/",
"Cake\Test\": "vendor/cakephp/cakephp/tests/"
}
},

**Comment by josbeir** [comment]
I don't think this has anything to do with this plugin as composer installation is handled by composer and the packagist.org repository.

Make sure that you are
- installing the plugin from the right location (in your application root folder)
- You are installing the correct version of the plugin (^2.0 for cake4, ^1.0 for cake3)
- Composer doesn't fail with an error during installation

```
$ composer create-project --prefer-dist cakephp/app:^4.0 test
$ cd test
$ composer require josbeir/cakephp-filesystem
$ cat composer.json

...
    "type": "project",
    "license": "MIT",
    "require": {
        "php": ">=7.2",
        "cakephp/cakephp": "^4.0",
        "cakephp/migrations": "^3.0",
        "cakephp/plugin-installer": "^1.2",
        "josbeir/cakephp-filesystem": "^2.0",
        "mobiledetect/mobiledetectlib": "^2.8"
    },
    "require-dev": {
        "cakephp/bake": "^2.0.3",
        "cakephp/cakephp-codesniffer": "~4.0.0",
...
```

All works as expected.
Also using vscode here, works great (with intelephsense plugin)

Good luck!
