### ISSUE TITLE
S3 Adapter

### ISSUE THREAD

**Issue by bergwerkweb** [josbeir/cakephp-filesystem#6]
Hi there,

first of all - thanks for this plugin, for local file upload it really works quick and easy! :-)

However when trying to implement the Flysystem AwsS3Adapter I cannot figure out how to do this correctly? It seems the S3 Adapter needs an "S3 Client" object to initialize the adapter and not just an array of options? Where can i configure that? Or is this something that is not yet implemented at all?

$client = new S3Client([
    'credentials' => [
        'key'    => 'your-key',
        'secret' => 'your-secret',
    ],
    'region' => 'your-region',
    'version' => 'latest|version',
]);

$adapter = new AwsS3Adapter($client, 'your-bucket-name', 'optional/path/prefix');

**Comment by josbeir** [comment]
This should work ok, please see the [defaultConfig](https://github.com/josbeir/cakephp-filesystem/blob/cakephp-4.x/src/Filesystem.php#L54) array and how to define adapters and pass configuration to the adapter

Here's a a quick (untested) example on how to apply it to the plugin configuration to get you going (based on [this](https://github.com/thephpleague/flysystem-aws-s3-v3) adapter):

```php
<?php
$awsBucket = 'mybucket';
$awsOptions = [
    'credentials' => [
        'key'    => 'your-key',
        'secret' => 'your-secret'
    ],
    'region' => 'your-region',
    'version' => 'latest|version',
];

return [
    'Filesystem' => [
        'aws' => [
            'adapter' => 'League\Flysystem\AwsS3v3\AwsS3Adapter',
            'adapterArguments' => [ $awsOptions, $awsBucket ]
        ]
    ]
];
```

**Comment by bergwerkweb** [comment]
thanks for the quick response, seems to work - almost - fine. However, it seems you have to initialize the S3Client first.

The following worked for me (directly in config/filesystems.php):

$S3client = new \Aws\S3\S3Client([
    'credentials' => [
        'key'    => 'your-key',
        'secret' => 'your-secret'
    ],
    'region' => 'your-region',
    'version' => 'latest',
]);

$bucketname = "your-bucket";
$subfolder = "your-subfolder";

return [
    'Filesystem' => [

        'aws' => [
            'adapter' => '\League\Flysystem\AwsS3v3\AwsS3Adapter',
            'adapterArguments' => [
				$S3client,
				$bucketname,
				$subfolder
			]
        ],
    ]
];

**Comment by josbeir** [comment]
Thats great, yeah i just constructed a small example based off memory :-)
If you have the time you can always add a section of this to the readme file.
